{{- if .Values.brokerClient.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: {{ .Values.brokerClient.namespace }}
  labels:
    app.kubernetes.io/name: rabbitmq
    {{- include "mop-client.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.brokerClient.service.ports.amqp }}
    - name: epmd
      port: 4369
    - name: dist
      port: 25672
{{- end }}
