
  {{- if .Values.brokerClient.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: {{ .Values.brokerClient.namespace }}
  labels:
    app.kubernetes.io/name: rabbitmq
    {{- include "mop-client.labels" . | nindent 4 }}
{{- end }}
