{{- if .Values.mopValidator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mop-validator-secret
  namespace: {{ .Values.mopValidator.namespace }}
  labels:
    app: mop-validator
    {{- include "mop-client.labels" . | nindent 4 }}
type: Opaque
stringData: {}
{{- end }}
