{{- if and .Values.mopClientAnonymization.enabled .Values.mopClientAnonymization.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mop-anonymization-hpa
  namespace: {{ .Values.mopClientAnonymization.namespace }}
  labels:
    app: mop-anonymization
    {{- include "mop-client.labels" . | nindent 4 }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mop-anonymization

  minReplicas: {{ .Values.mopClientAnonymization.hpa.minReplicas }}
  maxReplicas: {{ .Values.mopClientAnonymization.hpa.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mopClientAnonymization.hpa.targetCPUUtilizationPercentage }}
{{- end }}
