{{- if .Values.mopGateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mop-gateway-config
  namespace: {{ .Values.mopGateway.namespace }}
  labels:
    app: mop-gateway
    {{- include "mop-client.labels" . | nindent 4 }}
data: {}
{{- end }}
