{{- if .Values.mopClientAnonymization.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mop-anonymization
  namespace: {{ .Values.mopClientAnonymization.namespace }}
  labels:
    app: mop-anonymization
    {{- include "mop-client.labels" . | nindent 4 }}

spec:
  type: {{ .Values.mopClientAnonymization.service.type }}
  ports:
    - name: http
      port: {{ .Values.mopClientAnonymization.service.port }}
      targetPort: {{ .Values.mopClientAnonymization.service.port }}
  selector:
    app: mop-anonymization
{{- end }}
