{{- if and .Values.global.registryCredentials.enabled .Values.global.registryCredentials.username .Values.global.registryCredentials.password }}
{{- $secretName := .Values.global.registryCredentials.secretName | default "ghcr-secret" -}}
{{- $server := .Values.global.registryCredentials.server | default "ghcr.io" -}}
{{- $username := .Values.global.registryCredentials.username -}}
{{- $password := .Values.global.registryCredentials.password -}}
{{- $email := .Values.global.registryCredentials.email | default "devops@example.com" -}}

{{- range $app, $cfg := .Values }}
{{- if and $cfg.enabled $cfg.namespace }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $cfg.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/created-by: "helm"
    app.kubernetes.io/part-of: {{ $.Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $server $username $password $email (printf "%s:%s" $username $password | b64enc) | b64enc }}
---
{{- end }}
{{- end }}

{{- end }}
